### ISSUE TITLE
Links with errors - Onebitcode

### ISSUE THREAD

**Issue by kleytonmr** [evertonlopesc/Ruby-Roadmap#5]
Hi, it looks like none of the Onebitcode links are working anymore due to a platform change. I saved all the Ruby and Rails course links, but unfortunately, they don't work anymore. It looks like my account has lost access to all free courses due to a platform change. In the future, I will open a PR to suggest removing the old links that don't work. That it.

**Comment by evertonlopesc** [comment]
Hi, @kleytonmr!
Thanks for notification me, I'll change the links for other content.

**Comment by evertonlopesc** [comment]
Done!
